site_name: Personal Knowledge Repository
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Automatic-KS: automaticks/index.md
  - Price Confidence: price-confidence/index.md
  - Meeting Notes: meeting-notes/index.md
  - Liability Engine: liabilityengine/index.md
